/**
 * Emergency Profile — critical health info card with share + edit.
 */
import React, { useState } from 'react';
import {
  View,
  Text,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  Alert,
} from 'react-native';
import { router } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { colors, spacing, radius } from '../components/design-tokens';

interface EmergencyData {
  name: string;
  dob: string;
  bloodGroup: string;
  allergies: string[];
  conditions: string[];
  medications: string[];
  emergencyContact: {
    name: string;
    relation: string;
    phone: string;
  };
}

const INITIAL_DATA: EmergencyData = {
  name: 'Demo User',
  dob: '15 March 1978',
  bloodGroup: 'O+',
  allergies: ['Sulfa drugs'],
  conditions: ['Type 2 Diabetes (dx 2019)', 'Dyslipidemia (2022)'],
  medications: [
    'Atorvastatin 10mg — 0-0-1',
    'Metformin 500mg — 1-0-1',
    'Vitamin D3 60000 IU — weekly',
  ],
  emergencyContact: {
    name: 'Priya Sharma',
    relation: 'Spouse',
    phone: '+91 98765 43210',
  },
};

export default function EmergencyScreen() {
  const [data, setData] = useState<EmergencyData>(INITIAL_DATA);
  const [editing, setEditing] = useState(false);
  const [editAllergies, setEditAllergies] = useState('');
  const [editConditions, setEditConditions] = useState('');
  const [editMedications, setEditMedications] = useState('');

  const startEdit = () => {
    setEditAllergies(data.allergies.join(', '));
    setEditConditions(data.conditions.join('\n'));
    setEditMedications(data.medications.join('\n'));
    setEditing(true);
  };

  const saveEdit = () => {
    setData({
      ...data,
      allergies: editAllergies.split(',').map((s) => s.trim()).filter(Boolean),
      conditions: editConditions.split('\n').map((s) => s.trim()).filter(Boolean),
      medications: editMedications.split('\n').map((s) => s.trim()).filter(Boolean),
    });
    setEditing(false);
    Alert.alert('Saved', 'Emergency profile updated.');
  };

  const shareEmergencyCard = async () => {
    try {
      const html = `
        <html>
        <head>
          <style>
            body { font-family: -apple-system, Arial, sans-serif; padding: 32px; color: #1a1a1a; }
            h1 { color: #dc2626; font-size: 24px; border-bottom: 2px solid #dc2626; padding-bottom: 8px; }
            h2 { font-size: 16px; color: #555; margin-top: 20px; margin-bottom: 8px; }
            .field { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #eee; }
            .label { color: #888; }
            .value { font-weight: 600; }
            .alert { background: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: 8px 12px; margin: 4px 0; color: #dc2626; font-weight: 500; }
            .item { padding: 4px 0; }
            .footer { margin-top: 32px; font-size: 11px; color: #aaa; text-align: center; }
          </style>
        </head>
        <body>
          <h1>🆘 Emergency Medical Profile</h1>
          
          <div class="field"><span class="label">Name</span><span class="value">${data.name}</span></div>
          <div class="field"><span class="label">Date of Birth</span><span class="value">${data.dob}</span></div>
          <div class="field"><span class="label">Blood Group</span><span class="value" style="color:#dc2626;font-size:18px;">${data.bloodGroup}</span></div>

          <h2>⚠️ Allergies</h2>
          ${data.allergies.map((a) => `<div class="alert">${a}</div>`).join('')}

          <h2>🩺 Chronic Conditions</h2>
          ${data.conditions.map((c) => `<div class="item">• ${c}</div>`).join('')}

          <h2>💊 Current Medications</h2>
          ${data.medications.map((m) => `<div class="item">• ${m}</div>`).join('')}

          <h2>📞 Emergency Contact</h2>
          <div class="field"><span class="label">Name</span><span class="value">${data.emergencyContact.name} (${data.emergencyContact.relation})</span></div>
          <div class="field"><span class="label">Phone</span><span class="value" style="color:#0891b2;">${data.emergencyContact.phone}</span></div>

          <div class="footer">
            Generated by OSLO Health · ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
          </div>
        </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Share Emergency Profile',
        UTI: 'com.adobe.pdf',
      });
    } catch (err) {
      console.error('Share failed:', err);
      Alert.alert('Error', 'Could not share emergency profile.');
    }
  };

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={styles.back}>‹ Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>🆘 Emergency Profile</Text>
          <Text style={styles.subtitle}>
            Share this screen with emergency responders
          </Text>
        </View>

        {/* Identity */}
        <View style={styles.card}>
          <View style={styles.row}>
            <Text style={styles.label}>Name</Text>
            <Text style={styles.value}>{data.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date of Birth</Text>
            <Text style={styles.value}>{data.dob}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Blood Group</Text>
            <View style={styles.badge}>
              <Text style={styles.badgeText}>{data.bloodGroup}</Text>
            </View>
          </View>
        </View>

        {/* Allergies */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>⚠️ Allergies</Text>
          {editing ? (
            <TextInput
              style={styles.editInput}
              value={editAllergies}
              onChangeText={setEditAllergies}
              placeholder="Comma-separated: Sulfa drugs, Penicillin"
              placeholderTextColor={colors.textTertiary}
            />
          ) : (
            data.allergies.map((a, i) => (
              <View key={i} style={styles.alertRow}>
                <Text style={styles.alertText}>{a}</Text>
              </View>
            ))
          )}
        </View>

        {/* Conditions */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>🩺 Chronic Conditions</Text>
          {editing ? (
            <TextInput
              style={[styles.editInput, { height: 80 }]}
              value={editConditions}
              onChangeText={setEditConditions}
              placeholder="One per line"
              placeholderTextColor={colors.textTertiary}
              multiline
            />
          ) : (
            data.conditions.map((c, i) => (
              <Text key={i} style={styles.listItem}>• {c}</Text>
            ))
          )}
        </View>

        {/* Current Medications */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>💊 Current Medications</Text>
          {editing ? (
            <TextInput
              style={[styles.editInput, { height: 100 }]}
              value={editMedications}
              onChangeText={setEditMedications}
              placeholder="One per line"
              placeholderTextColor={colors.textTertiary}
              multiline
            />
          ) : (
            data.medications.map((m, i) => (
              <Text key={i} style={styles.listItem}>• {m}</Text>
            ))
          )}
        </View>

        {/* Emergency Contact */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>📞 Emergency Contact</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name</Text>
            {editing ? (
              <TextInput
                style={styles.inlineInput}
                value={data.emergencyContact.name}
                onChangeText={(v) =>
                  setData({ ...data, emergencyContact: { ...data.emergencyContact, name: v } })
                }
              />
            ) : (
              <Text style={styles.value}>{data.emergencyContact.name}</Text>
            )}
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Relation</Text>
            <Text style={styles.value}>{data.emergencyContact.relation}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Phone</Text>
            {editing ? (
              <TextInput
                style={styles.inlineInput}
                value={data.emergencyContact.phone}
                onChangeText={(v) =>
                  setData({ ...data, emergencyContact: { ...data.emergencyContact, phone: v } })
                }
                keyboardType="phone-pad"
              />
            ) : (
              <Text style={[styles.value, { color: colors.accent }]}>
                {data.emergencyContact.phone}
              </Text>
            )}
          </View>
        </View>

        {/* Action buttons */}
        <View style={styles.actions}>
          <TouchableOpacity style={styles.shareBtn} onPress={shareEmergencyCard}>
            <Text style={styles.shareBtnText}>📤 Share Emergency Card</Text>
          </TouchableOpacity>

          {editing ? (
            <View style={{ flexDirection: 'row', gap: spacing(3) }}>
              <TouchableOpacity
                style={[styles.editBtn, { flex: 1 }]}
                onPress={() => setEditing(false)}
              >
                <Text style={styles.editText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.shareBtn, { flex: 1 }]}
                onPress={saveEdit}
              >
                <Text style={styles.shareBtnText}>💾 Save</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <TouchableOpacity style={styles.editBtn} onPress={startEdit}>
              <Text style={styles.editText}>✏️ Edit Emergency Profile</Text>
            </TouchableOpacity>
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bgPrimary },
  scroll: { paddingBottom: spacing(10) },
  header: {
    padding: spacing(5),
    borderBottomWidth: 1,
    borderBottomColor: colors.borderTertiary,
  },
  back: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: '500',
    marginBottom: spacing(2),
  },
  title: {
    fontSize: 22,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: spacing(1),
  },
  card: {
    margin: spacing(5),
    marginBottom: 0,
    padding: spacing(4),
    borderRadius: radius.lg,
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.borderTertiary,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: spacing(3),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing(2),
  },
  label: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  value: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  badge: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1),
    borderRadius: radius.pill,
    backgroundColor: colors.statusFlagBg,
  },
  badgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.statusFlag,
  },
  alertRow: {
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    borderRadius: radius.md,
    backgroundColor: colors.statusFlagBg,
    marginBottom: spacing(1),
  },
  alertText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.statusFlag,
  },
  listItem: {
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 22,
    marginBottom: spacing(1),
  },
  actions: {
    margin: spacing(5),
    gap: spacing(3),
  },
  shareBtn: {
    padding: spacing(4),
    borderRadius: radius.lg,
    backgroundColor: colors.accent,
    alignItems: 'center',
  },
  shareBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textOnDark,
  },
  editBtn: {
    padding: spacing(4),
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
    alignItems: 'center',
  },
  editText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  editInput: {
    borderRadius: radius.md,
    backgroundColor: colors.bgPrimary,
    padding: spacing(3),
    fontSize: 14,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.borderSecondary,
  },
  inlineInput: {
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
    fontSize: 14,
    fontWeight: '500',
    color: colors.textPrimary,
    paddingVertical: spacing(1),
    paddingHorizontal: spacing(2),
    minWidth: 120,
    textAlign: 'right',
  },
});
